# Generated by Django 4.1.4 on 2022-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=100)),
                ('cropimg', models.ImageField(upload_to='exercise_pics')),
                ('cropdetails', models.TextField()),
            ],
        ),
    ]
